apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compliance-dvn-worker-data
  labels:
    app.kubernetes.io/name: compliance-dvn-worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
